package com.amorabot.inscripted.components.Items.modifiers;

import lombok.Getter;

@Getter
public enum InscriptionID {
    //=====RELIC INSCRIPTIONS=====
    //BLEEDING HEART INSCRIPTIONS
    BLHA_BLEED_CHANCE("1 RELIC BLEED +% x +", 1, true),
    BLHA_BLD_DMG("1 RELIC BLEED_DAMAGE +% - +", 1, true),

    //OMINOUS TWIG INSCRIPTIONS
    OMTW_ABYSSAL("1 RELIC ABYSSAL_DAMAGE ++ -/- +", 1, false),

    //CORRUPTORS WRAPPINGS INSCRIPTIONS
    COWR_WARD("1 RELIC WARD %+ - +", 1, false),
    COWW_STRENGTH("1 RELIC STRENGTH ++ - -", 1, true),
    COWR_MORE_WARD("1 RELIC WARD %* - +", 1, true),

    //APPROACHING WINTER INSCRIPTIONS
    APWI_WALK_SPEED("1 RELIC WALK_SPEED ++ - -", 1, true),
    APWI_COLD_RES("1 RELIC COLD_RESISTANCE +% - +", 1, true),
    APWI_FIRE_RES("1 RELIC FIRE_RESISTANCE +% - -", 1, true),
    APWI_COLD_DMG("1 RELIC COLD_DAMAGE %+ - +", 1, true),
    APWI_FLAT_COLD("1 RELIC COLD_DAMAGE ++ -/- +", 1, true),

    //BLIND RAGE INSCRIPTIONS
    BLRA_ACCURACY("1 RELIC ACCURACY ++ - -", 1, true),
    BLRA_LESS_HEALTH("1 RELIC HEALTH %* x -", 1, true),

    //EYE OF THE STORM INSCRIPTIONS
    EOTS_LIGHTNING_RES("1 RELIC LIGHTNING_RESISTANCE +% - -", 1, true),
    EOTS_MAX_LIGHTNING_RES("1 RELIC MAX_LIGHTNING_RESISTANCE +% - +", 1, true),

    //TIN FOIL HELMET INSCRIPTIONS
    TIFO_HELMET_INTELLIGENCE("1 RELIC INTELLIGENCE ++ - -", 1, true),

    //QUEEN OF THE FOREST INSCRIPTIONS
    QOTF_REDU_WALK_SPEED("1 RELIC WALK_SPEED %+ - -", 1, true),

    //SCARLET DANCER INSCRIPTIONS
    SCDA_PHYS("1 RELIC PHYSICAL_DAMAGE %+ - +", 1, false),
    SCDA_LESS_ARMOR("1 RELIC ARMOR %* x -", 1, true),
    SCDA_LIFE_ON_HIT("1 RELIC LIFE_ON_HIT ++ - +", 1, true),

    //IMMORTAL FLESH INSCRIPTIONS
    IMFL_INC_REGEN("1 RELIC HEALTH_REGEN %+ - +", 1, true),
    IMFL_FLAT_REGEN("1 RELIC HEALTH_REGEN ++ - +", 1, true),

    //GODHEAD SET INSCRIPTIONS
    GODHEAD_LESS_FIRE_RES("1 RELIC FIRE_RESISTANCE %* x -", 1, true),
    GODHEAD_LESS_LIGHTNING_RES("1 RELIC LIGHTNING_RESISTANCE %* x -", 1, true),
    GODHEAD_LESS_COLD_RES("1 RELIC COLD_RESISTANCE %* x -", 1, true),

    //TRINITY INSCRIPTIONS
    TRINITY_LESS_HEALTH("1 RELIC HEALTH %* x -", 1, true),
    TRINITY_LESS_WARD("1 RELIC WARD %* x -", 1, true),

    //BODY INSCRIPTIONS
    THE_BODY_INC_ARMOR("1 RELIC ARMOR %+ - +", 1, false),

    //MIND INSCRIPTIONS
    THE_MIND_INC_WARD("1 RELIC WARD %+ - +", 1, false),

    //SOUL INSCRIPTIONS
    THE_SOUL_INC_DODGE("1 RELIC DODGE ++ - +", 1, false),

    //MAD BUTCHER INSCRIPTIONS
    MABU_BLEED_CHANCE("1 RELIC BLEED +% - +", 1, true),

   //HEADSMAN BLADE INSCRIPTIONS
    HEBL_BLEED_DMG("1 RELIC BLEED_DAMAGE +% - +", 1, true),
    HEBL_SHRED("1 RELIC SHRED +% x +", 1, true),

    //EXECUTIONERS MASK INSCRIPTIONS
    EXMA_FLAT_PHYS("1 RELIC PHYSICAL_DAMAGE ++ -/- +", 1, true),
    EXMA_SHRED("1 RELIC SHRED +% - +", 1, true),
    EXMA_CRIT_DMG("1 RELIC CRITICAL_DAMAGE +% - +", 1, true),

    //ELUSIVE SHADOW INSCRIPTIONS
    ELSH_CRIT_CHANCE("1 RELIC CRITICAL_CHANCE +% - +", 1, true),

    //BROKEN FAITH INSCRIPTIONS
    BRFA_ABYSS_FLAT("1 RELIC ABYSSAL_DAMAGE ++ -/- +", 1, false),
    BRFA_ABYSS_PERCENT("1 RELIC ABYSSAL_DAMAGE %+ - +", 1, true),
    BRFA_LESS_HPS("1 RELIC HEALTH_REGEN %* x -", 1, true),

    //DRUIDIC PELTS INSCRIPTIONS
    DRPE_HEALTH_REGEN("1 RELIC HEALTH_REGEN ++ - +", 1, true),

    //META RELIC MODS
//    @Meta(convertedStat = PlayerStats.STRENGTH, convertedValueType = ValueTypes.FLAT, rate = 10)
    HELLFORGE_STRENGTH_TO_FIRE_DMG("1 RELIC FIRE_DAMAGE ++ -/- +", 1, true),
//    @Meta(convertedStat = PlayerStats.DEXTERITY, convertedValueType = ValueTypes.FLAT, rate = 5)
    QOTF_DEX_TO_WS("1 RELIC WALK_SPEED %+ x +", 1, true),
//    @Meta(convertedStat = PlayerStats.WARD, convertedValueType = ValueTypes.FLAT, rate = 600)
    BROKEN_FAITH_WARD_TO_ABYSS("1 RELIC ABYSSAL_DAMAGE ++ -/- +", 1, true),

    //=====KEYSTONES=====
    LETHAL_STRIKES("* RELIC KEYSTONE LETHAL_STRIKES", 0, true),
    FORBIDDEN_PACT("* RELIC KEYSTONE FORBIDDEN_PACT", 0, true),
    PERMAFROST("* RELIC KEYSTONE PERMAFROST", 0, true),
    BERSERK("* RELIC KEYSTONE BERSERK", 0, true),
    THUNDERSTRUCK("* RELIC KEYSTONE THUNDERSTRUCK", 0, true),
    BLOOD_PACT("* RELIC KEYSTONE BLOOD_PACT", 0, true),
    ORGAN_FAILURE("* RELIC KEYSTONE ORGAN_FAILURE", 0, true),
    FIRE_ATTUNEMENT("* RELIC KEYSTONE FIRE_ATTUNEMENT", 0, true),
    LIGHTNING_ATTUNEMENT("* RELIC KEYSTONE LIGHTNING_ATTUNEMENT", 0, true),
    COLD_ATTUNEMENT("* RELIC KEYSTONE COLD_ATTUNEMENT", 0, true),
    ELEMENTAL_BLESSING("* RELIC KEYSTONE ELEMENTAL_BLESSING", 0, true),
    AGNOSTIC("* RELIC KEYSTONE AGNOSTIC", 0, true),
    WINDS_OF_CHANGE("* RELIC KEYSTONE WINDS_OF_CHANGE", 0, true),

    //=====EFFECTS=====
    THRILL_OF_THE_HUNT("* RELIC EFFECT THRILL_OF_THE_HUNT", 0, true),
    ADRENALINE_RUSH("* RELIC EFFECT ADRENALINE_RUSH", 0, true),
    GRACEFUL_LANDING("* RELIC EFFECT GRACEFUL_LANDING", 0, true),
    SADISM("* RELIC EFFECT SADISM", 0, true),
    COUP_DE_GRACE("* RELIC EFFECT COUP_DE_GRACE", 0, true),
    OPPORTUNIST("* RELIC EFFECT OPPORTUNIST", 0, true),
    OVERDRIVE("* RELIC EFFECT OVERDRIVE", 0, true);


    private String definitionString;
    private String displayName;
    private int totalTiers;
    private boolean global;
    private boolean meta;
    private boolean positive;


    InscriptionID(String definitionString, int tiers, boolean isGlobal){

    }
}
