name: RPGElements
version: '0.2'
main: com.amorabot.rpgelements.RPGElements
api-version: 1.19
permissions:
    pluginstudies.fly:
      description: Allows the player to use the /fly command
    pluginstudies.menu:
      description: Allows the player to open various menus.
    pluginstudies.builder:
      description: Gives the player the building privileges.
commands:
  updatenbt:
    description: Updates a item's item level NBT data.
    usage: /updatenbt
  identify:
    description: Identifies a custom item.
    usage: /identify
    aliases: [id]
  generateweapon:
    description: generates a custom weapon.
    usage: /generateweapon
    aliases: [weapon, genw]
  resetattributes:
    description: resets the attribute data for the sender.
    usage: /resetatt
  getnbt:
    description: gets a specified NBT data tag.
    usage: /getnbt
  recolor:
    description: recolors a item's display name.
    usage: /recolor
  editmods:
    description: modifiers JSON edit interface
    usage: /editmods
  generatearmor:
    description: generates a custom armor.
    usage: /generatearmor
    aliases: [ armor, gena ]
  show:
    description: shows the held item in chat
    usage: /show