name: Inscripted
version: '0.2'
main: com.amorabot.inscripted.Inscripted
api-version: 1.21
permissions:

commands:
  color:
    description: Command for testing color and text components
    usage: /color
  cast:
    description: Casts the selected player ability
    usage: /cast
  orb:
    description: Command for easy currency access.
    usage: /orb
  updatenbt:
    description: Updates a item's item level NBT data.
    usage: /updatenbt
  identify:
    description: Identifies a custom item.
    usage: /identify
    aliases: [id]
  resetattributes:
    description: resets the attribute data for the sender.
    usage: /resetatt
  stats:
    description: displays player stats in chat.
    usage: /stats
  generateitem:
    description: generates a custom item.
    usage: /generateitem
    aliases: [item]
  show:
    description: shows the held item in chat
    usage: /show
  template:
    description: template command for testing arbritraty functionalities
    usage: /template
  mob:
    description: spawning custom mobs individually for tests
    usage: /mob