name: Inscripted
version: '0.2'
main: com.amorabot.inscripted.Inscripted
api-version: 1.19
permissions:

commands:
  updatenbt:
    description: Updates a item's item level NBT data.
    usage: /updatenbt
  identify:
    description: Identifies a custom item.
    usage: /identify
    aliases: [id]
  generateweapon:
    description: generates a custom weapon.
    usage: /generateweapon
    aliases: [weapon, genw]
  resetattributes:
    description: resets the attribute data for the sender.
    usage: /resetatt
  getnbt:
    description: gets a specified NBT data tag.
    usage: /getnbt
  recolor:
    description: recolors a item's display name.
    usage: /recolor
  editmods:
    description: modifiers JSON edit interface
    usage: /editmods
  generatearmor:
    description: generates a custom armor.
    usage: /generatearmor
    aliases: [ armor, gena ]
  show:
    description: shows the held item in chat
    usage: /show
  template:
    description: template command for testing arbritraty functionalities
    usage: /template
  mob:
    description: spawning custom mobs individually for tests
    usage: /mob