package com.amorabot.rpgelements.events;

public enum ItemUsage {

//    LEFT_CLICK_AIR,
//    LEFT_CLICK_BLOCK,
//    LEFT_CLICK_ENTITY,
//
//    RIGHT_CLICK_AIR,
//    RIGHT_CLICK_BLOCK,
//    RIGHT_CLICK_ENTITY,

//    INVENTORY_SWAP_PICKUP,
//    INVENTORY_SWAP_PLACE,
//    INVENTORY_PLACE_ITEM,
//    INVENTORY_PICKUP_ITEM,
//
//    CONSUME_ITEM,

    UNIDED_ARMOR,
    ARMOR_UNEQUIP,
    ARMOR_LEFT_CLICK_AIR,
    ARMOR_LEFT_CLICK_BLOCK,
    ARMOR_RIGHT_CLICK_AIR,
    ARMOR_RIGHT_CLICK_BLOCK,
    ARMOR_SHIFTING_FROM_INV,
    ARMOR_SHIFTING_TO_INV,
//    ARMOR_SHIFTING_WITHIN_INV,

    UNIDED_WEAPON,
    WEAPON_EQUIP,
    WEAPON_UNEQUIP,
    WEAPON_LEFT_CLICK_AIR,
    WEAPON_LEFT_CLICK_BLOCK,
    WEAPON_RIGHT_CLICK_AIR,
    WEAPON_RIGHT_CLICK_BLOCK,
    WEAPON_SHIFTING_FROM_INV,
    WEAPON_SHIFTING_TO_INV,
//    WEAPON_SHIFTING_WITHIN_INV,

    NONE
}
